"""Generate Sources/Terminal-ios/Packages/BundledCatalog.swift from catalog/.

The catalog is the single, frozen package source. This script:
  1. reads catalog/catalog.json,
  2. computes the SHA-256 of every payload under catalog/payloads/ and writes
     the digest back into catalog.json (so the manifest is self-describing),
  3. emits BundledCatalog.swift with the manifest JSON and every payload body
     embedded as Swift string literals.

Embedding as Swift literals (instead of bundle resources) keeps the payloads
available to the unit tests, which run without an app bundle, and removes any
dependency on how the Xcode file-system synchronized group treats .sh/.json
files.

Run from the repository root:  python support/generate_catalog.py
"""

import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = ROOT / "catalog" / "catalog.json"
PAYLOAD_DIR = ROOT / "catalog" / "payloads"
OUTPUT = ROOT / "Sources" / "Terminal-ios" / "Packages" / "BundledCatalog.swift"


def sha256_hex(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def swift_literal(text: str, indent: str = "        ") -> str:
    """A Swift multi-line string literal that cannot be broken by backslashes."""
    if '"""' in text:
        raise SystemExit("payload contains a triple quote; use single-line encoding")
    escaped = text.replace("\\", "\\\\")
    body = "\n".join(indent + line if line else "" for line in escaped.split("\n"))
    return f'{indent}"""\n{body}\n{indent}"""'


def main() -> int:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    payloads: dict[str, str] = {}

    for entry in catalog["entries"]:
        payload = entry.get("payload")
        if not payload:
            entry["sha256"] = None
            continue
        path = ROOT / "catalog" / payload
        if not path.exists():
            print(f"missing payload: {path}", file=sys.stderr)
            return 1
        body = path.read_text(encoding="utf-8")
        payloads[payload] = body
        entry["sha256"] = sha256_hex(body)
        print(f"{entry['name']:<16} {entry['sha256'][:16]}…  {len(body.encode('utf-8'))}B")

    # Write the digests back so catalog.json stays the readable source of truth.
    CATALOG.write_text(
        json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    manifest = json.dumps(catalog, indent=2, ensure_ascii=False)

    payload_blocks = []
    for path, body in sorted(payloads.items()):
        payload_blocks.append('        "' + path + '": ' + swift_literal(body))
    payload_section = ",\n".join(payload_blocks)

    triple = '"' * 3
    # NOTE: the opening delimiter comes from swift_literal(), so the header must
    # stop at `= ` - emitting it here too closes the literal immediately and the
    # JSON ends up parsed as Swift code.
    header = (
        "// Copyright © 2026 Liu-bits. All rights reserved.\n"
        "\n"
        "// Generated by support/generate_catalog.py - do not edit by hand.\n"
        "// Source of truth: catalog/catalog.json plus catalog/payloads/*.\n"
        "//\n"
        "// The manifest and every payload are compiled into the binary, so installing a\n"
        "// package needs no network and cannot be tampered with after the build.\n"
        "\n"
        "enum BundledCatalog {\n"
        "\n"
        "    /// Raw manifest JSON, byte-identical to catalog/catalog.json.\n"
        "    static let json = "
    )

    output = (
        header
        + swift_literal(manifest, indent="    ")
        + "\n\n    /// Payload bodies by catalog-relative path.\n"
        + "    static let payloads: [String: String] = [\n"
        + payload_section
        + "\n    ]\n}\n"
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output, encoding="utf-8")
    print("wrote " + str(OUTPUT.relative_to(ROOT)) + " (" + str(len(payloads)) + " payload(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
