// Copyright © 2026 Liu-bits. All rights reserved.

// Generated by support/generate_catalog.py - do not edit by hand.
// Source of truth: catalog/catalog.json plus catalog/payloads/*.
//
// The manifest and every payload are compiled into the binary, so installing a
// package needs no network and cannot be tampered with after the build.

enum BundledCatalog {

    /// Raw manifest JSON, byte-identical to catalog/catalog.json.
    static let json = """
    """
    {
      "schema": 1,
      "name": "Terminal-ios bundled catalog",
      "generated": "2026-09-26",
      "entries": [
        {
          "name": "hello",
          "version": "1.0.0",
          "kind": "script",
          "summary": "greet someone - the smallest catalog package",
          "provides": [
            "hello"
          ],
          "payload": "payloads/hello.sh",
          "sha256": "8d6a9ad9b20bdf837fb377e7005a8dcdb92bfbc8c07329b6e536105b0a91b621",
          "source": "Terminal-ios",
          "license": "MIT"
        },
        {
          "name": "sysinfo",
          "version": "1.0.0",
          "kind": "script",
          "summary": "one screen of facts about the sandbox",
          "provides": [
            "sysinfo"
          ],
          "payload": "payloads/sysinfo.sh",
          "sha256": "4b00985c7947307986dbdda52c8602153da12b1d9f9899e2d0d21a39bf040ea4",
          "source": "Terminal-ios",
          "license": "MIT"
        },
        {
          "name": "mkproject",
          "version": "1.0.0",
          "kind": "script",
          "summary": "scaffold a project directory (src, tests, README)",
          "provides": [
            "mkproject"
          ],
          "payload": "payloads/mkproject.sh",
          "sha256": "3ff37e9e4667f950fb182da49614b99710ccc29399fc04851d5cc00966fb86ce",
          "source": "Terminal-ios",
          "license": "MIT"
        },
        {
          "name": "backup",
          "version": "1.0.0",
          "kind": "script",
          "summary": "timestamped directory backup into .backups",
          "provides": [
            "backup"
          ],
          "payload": "payloads/backup.sh",
          "sha256": "29c39a0f9fc84fbc7213b1c587bcd489d30ed6af59ca216819aade41bf05192c",
          "source": "Terminal-ios",
          "license": "MIT"
        },
        {
          "name": "sum",
          "version": "1.0.0",
          "kind": "script",
          "summary": "add the integers on stdin",
          "provides": [
            "sum"
          ],
          "payload": "payloads/sum.sh",
          "sha256": "da2fffc2974a2e1c0d67cb8f12aca4fd34a00afdafb7fc33ba3b3c8dfe9bd7ec",
          "source": "Terminal-ios",
          "license": "MIT"
        },
        {
          "name": "python-runtime",
          "version": "3.13.5",
          "kind": "runtime",
          "summary": "CPython built for the bundled WASM engine (no JIT)",
          "provides": [
            "python3",
            "python",
            "py",
            "pip",
            "pip3"
          ],
          "payload": null,
          "sha256": null,
          "source": "python/cpython (wasm32-wasi build)",
          "license": "PSF-2.0"
        },
        {
          "name": "mingw-toolchain",
          "version": "16.1.0",
          "kind": "toolchain",
          "summary": "GCC/MinGW-style C toolchain targeting WASM (never native Mach-O)",
          "provides": [
            "gcc",
            "cc",
            "clang",
            "make"
          ],
          "payload": null,
          "sha256": null,
          "source": "mingw-w64 / llvm (wasm32-wasi build)",
          "license": "GPL-3.0-or-later"
        }
      ]
    }
    """

    /// Payload bodies by catalog-relative path.
    static let payloads: [String: String] = [
        "payloads/backup.sh":         """
        # backup <dir> [dest] - copy a directory into .backups with a timestamp.
        target=$1
        dest=$2
        if [ -z "$target" ]; then
          echo "usage: backup <dir> [dest]"
          exit 2
        fi
        if [ ! -d "$target" ]; then
          echo "backup: $target: not a directory"
          exit 1
        fi
        if [ -z "$dest" ]; then
          dest=.backups
        fi
        mkdir -p "$dest"
        stamp=$(date +%Y%m%d-%H%M%S)
        cp -r "$target" "$dest/$target-$stamp"
        echo "backed up $target -> $dest/$target-$stamp"

        """,
        "payloads/hello.sh":         """
        # hello [name] - greet someone. The smallest possible catalog package.
        name=$1
        if [ -z "$name" ]; then
          name=world
        fi
        echo "hello, $name"

        """,
        "payloads/mkproject.sh":         """
        # mkproject <name> - scaffold a tiny project directory.
        name=$1
        if [ -z "$name" ]; then
          echo "usage: mkproject <name>"
          exit 2
        fi
        if [ -d "$name" ]; then
          echo "mkproject: $name already exists"
          exit 1
        fi
        mkdir -p "$name/src"
        mkdir -p "$name/tests"
        echo "# $name" > "$name/README.md"
        echo "created $name/ with src/ tests/ README.md"

        """,
        "payloads/sum.sh":         """
        # sum - add the integers arriving on stdin.
        # usage: cat numbers.txt | sum
        total=0
        while read line; do
          if [ -n "$line" ]; then
            total=$(expr $total + $line)
          fi
        done
        echo "total: $total"

        """,
        "payloads/sysinfo.sh":         """
        # sysinfo - one screen of facts about the sandbox this shell runs in.
        echo "Terminal-ios sysinfo"
        echo "--------------------"
        echo "kernel:   $(uname -s) $(uname -r)"
        echo "arch:     $(uname -m)"
        echo "cpus:     $(nproc)"
        echo "user:     $(whoami)"
        echo "cwd:      $(pwd)"
        echo "date:     $(date +%F) $(date +%T)"
        echo "uptime:   $(uptime)"
        echo "packages:"
        apt list | head -n 20

        """
    ]
}
