// Copyright © 2026 Liu-bits. All rights reserved.

// Generated by support/wasm_fixtures.py - do not edit by hand.
//
// Hand-assembled modules covering LEB128 encodings, block types, control
// flow, memory, data segments and a WASI import. Each one was validated with
// Node's WebAssembly implementation first, and the comment above every
// fixture records what Node returned - that is what the tests assert.

import Foundation

enum WasmFixtures {

    private static func decode(_ base64: String) -> [UInt8] {
        [UInt8](Data(base64Encoded: base64) ?? Data())
    }

    /// Node result: {"add": 42, "answer": 7}
    static let add: [UInt8] = decode("AGFzbQEAAAABBwFgAn9/AX8DAgEABgsCfwBBBwt/AUEACwcaAwNhZGQAAAZhbnN3ZXIDAAdjb3VudGVyAwEKCQEHACAAIAFqCw==")
    /// Node result: {"classify0": 10, "classify1": 20, "classify9": 30, "fib10": 55, "fib20": 6765}
    static let controlflow: [UInt8] = decode("AGFzbQEAAAABBgFgAX8BfwMDAgAABxICA2ZpYgAACGNsYXNzaWZ5AAEKVAI3AQV/QQAhAkEBIQNBACEEAkADQCAEIABODQEgAiADaiEFIAMhAiAFIQMgBEEBaiEEDAALCyACCxoAAkACQAJAIAAOAgABAgtBCg8LQRQPC0EeCw==")
    /// Node result: {"byte0": 119, "pages": 1, "roundtrip": 123456}
    static let memory: [UInt8] = decode("AGFzbQEAAAABCgJgAX8Bf2AAAX8DBAMAAAEFBAEBAQQHKAQGbWVtb3J5AgAJcm91bmR0cmlwAAAHYnl0ZV9hdAABBXBhZ2VzAAIKHQMOAEEAIAA2AgBBACgCAAsHACAALQAACwQAPwALCxABAEEQCwp3YXNtLWRhdGEK")
    /// Node result: {}
    static let spin: [UInt8] = decode("AGFzbQEAAAABBAFgAAADAgEABwsBB2ZvcmV2ZXIAAAoJAQcAA0AMAAsL")
    /// Node result: {"divide": 50}
    static let trap: [UInt8] = decode("AGFzbQEAAAABCQJgAX8Bf2AAAAMDAgABBxMCBmRpdmlkZQAABl9zdGFydAABChICCABByAEgAG0LBwBBABAAGgs=")
    /// Node result: {} stdout='hello from wasm\n'
    static let wasihello: [UInt8] = decode("AGFzbQEAAAABDAJgBH9/f38Bf2AAAAIjARZ3YXNpX3NuYXBzaG90X3ByZXZpZXcxCGZkX3dyaXRlAAADAgEBBQMBAAEHEwIGbWVtb3J5AgAGX3N0YXJ0AAEKEAEOAEEBQQBBAUHAABAAGgsLIwIAQQALCBAAAAAQAAAAAEEQCxBoZWxsbyBmcm9tIHdhc20K")
}
